Flowpack:
  ElasticSearch:
    clients:
        # default bundle that will be used if no more specific bundle name was supplied.
      default:
        - host: localhost
          port: 9200
          username: ''
          password: ''

    realtimeIndexing:
      enabled: TRUE
      client: default
    transfer:
      # The timeout in sections for connections between Flow and Elastic Search:
      connectionTimeout: 60

TYPO3:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          'Flowpack\ElasticSearch\Indexer\Object\Signal\Doctrine\EmitterAdapter':
            events: ['postUpdate', 'postPersist', 'postRemove']
            listener: 'Flowpack\ElasticSearch\Indexer\Object\Signal\Doctrine\EmitterAdapter'
